### ISSUE TITLE
Ledger connections aren't working

### ISSUE THREAD

**Issue by WorkerB33** [galaxies-labs/galaxy#1]
Trying to stake or send assets and it won't work at all. Keplr pops up but fails when passed to Ledger.   "data is invalid" is the error code

**Comment by maxxroot** [comment]
yes same problem

**Comment by ghost** [comment]
@maxxroot  @WorkerB33 

The problem with the Galaxy website has been fixed.

Galaxy daemon works fine. Is there a problem?
